# Generated by Django 2.0 on 2018-06-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '0002_cost_type_time_type'),
        ('competition_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='often',
            name='cost_type',
            field=models.ForeignKey(default=1, on_delete=True, to='quality_data.cost_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='often',
            name='time_type',
            field=models.ForeignKey(default=1, on_delete=True, to='quality_data.time_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='often',
            name='work_cost',
            field=models.FloatField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
