# Generated by Django 2.0 on 2018-06-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_system', '0002_auto_20180608_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='often',
            name='time_work',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='often',
            name='work_cost',
            field=models.FloatField(),
        ),
    ]
