# Generated by Django 2.0 on 2018-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20180608_2102'),
        ('order', '0005_auto_20180605_2105'),
        ('competition_system', '0004_auto_20180608_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='order',
            field=models.ForeignKey(default=3, on_delete=True, to='order.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='worker',
            field=models.ForeignKey(default=2, on_delete=True, to='user.worker'),
            preserve_default=False,
        ),
    ]
