# Generated by Django 2.0 on 2018-06-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_system', '0005_auto_20180608_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cost_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='quality_data.cost_type'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='order.order'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='time_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='quality_data.time_type'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='time_work',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='work_cost',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='worker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='user.worker'),
        ),
    ]
