# Generated by Django 2.0 on 2018-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_system', '0006_auto_20180612_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='sign',
            field=models.BooleanField(default=False),
        ),
    ]
