# Generated by Django 2.0 on 2018-06-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='specialization/academic subject')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
            },
        ),
    ]
