# Generated by Django 2.0 on 2018-06-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '0002_cost_type_time_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time_type',
            options={'verbose_name': 'time_type', 'verbose_name_plural': 'time_types'},
        ),
    ]
