# Generated by Django 2.0 on 2018-06-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '0003_auto_20180608_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost_type',
            options={'verbose_name': 'cost_type', 'verbose_name_plural': 'cost_types'},
        ),
    ]
