# Generated by Django 2.0 on 2018-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '__first__'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ForeignKey(default=1, on_delete=True, to='quality_data.category'),
            preserve_default=False,
        ),
    ]
