# Generated by Django 2.0 on 2018-05-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180531_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='quality_data.category'),
        ),
    ]
