# Generated by Django 2.0 on 2018-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality_data', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prise', models.FloatField(verbose_name='work price')),
                ('time', models.IntegerField(verbose_name='day number')),
            ],
            options={
                'verbose_name': 'competition',
                'verbose_name_plural': 'competitions',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='order name')),
                ('description', models.TextField()),
                ('category', models.OneToOneField(on_delete=True, to='quality_data.category')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='order',
            field=models.ForeignKey(on_delete=True, to='order.order'),
        ),
    ]
