# Generated by Django 2.0 on 2018-06-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_client_worker'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='choose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=True, to='user.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.OneToOneField(default=None, on_delete=True, to='quality_data.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='order name'),
        ),
    ]
