# Generated by Django 2.0 on 2018-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180602_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.OneToOneField(default=None, null=True, on_delete=True, to='quality_data.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='order name'),
        ),
    ]
