# Generated by Django 2.0 on 2018-06-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180604_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=True, to='quality_data.category'),
        ),
    ]
